language: go
sudo: false
go:
  - '1.12'
env:
  - GO111MODULE=on
cache:
  directories:
    - $GOPATH/pkg/mod
before_script: 
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.17.1